# Generated by Django 5.1.2 on 2024-10-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='password',
            field=models.CharField(default=12345678, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='image_url',
            field=models.URLField(default=87654321),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='link_to_purchase',
            field=models.URLField(default=1234567890),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='buyer',
            field=models.ManyToManyField(related_name='task1_game', to='task1.buyer'),
        ),
    ]
