# Generated by Django 5.1.2 on 2024-10-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_buyer_password_game_image_url_game_link_to_purchase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='link_to_purchase',
        ),
        migrations.AddField(
            model_name='buyer',
            name='login',
            field=models.BooleanField(default=False),
        ),
    ]
